Milestone_2
kessio/vet-clinic pull request #6
Opened 2022-11-08 15:11 UTC by Farida-Hamid

### Create a database based on a diagram:
- Created a file named `schema_based_on_diagram.sql` where we implement the database from the diagram.
- Joined tables from many-to-many relationships.
- Add the FK indexes.

2022-11-08 15:34 UTC, zieeco requested changes
Hi @Team,


Great job so far 👏 
You've done well, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- Nice schema.✔️
- Descriptive PR. ✔️


## Required Changes ♻️
_Check the comments under the review._


<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A

**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-08 15:34 UTC, zieeco commented on schema_based_on_diagram.sql
> +    );
- Let's create the "join table" for the many-to-many relationships between `medical_histories` and `treatments` 
Below is an example:
  ```sql
    CREATE TABLE medical_histories_has_treatments (
      medical_history_id int refrences medical_histories(id),
      treatment_id int refrences treatments(id),
      );
  ```
---
- Let's also ensure that all FOREIGN KEYS have indexes created e.g:

`CREATE INDEX ON medical_histories (patient_id);`

2022-11-09 08:13 UTC, Farida-Hamid commented on schema_based_on_diagram.sql
> +    );
We did include the instruction:
`CREATE INDEX ON medical_histories (patient_id);` in line 21.

2022-11-09 08:28 UTC, Nemwel-Boniface requested changes
## Hello @Farida-Hamid, @kessio  and @AbigiyaTY       :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job addressing some of the changes that were requested by a previous reviewer :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-09 08:28 UTC, Nemwel-Boniface commented on schema_based_on_diagram.sql
> +    );
- [ ] As requested by the previous reviewer @zieeco  and according to the project requirements, you are required to create a join table for your project. He was kind enough to point out to your team exactly which tables need the join table. Kindly create the join table as was previously requested.

![image](https://user-images.githubusercontent.com/86318284/200776893-3f4aa67d-04af-4f3a-ab6a-ea3ed640014b.png)

2022-11-09 08:28 UTC, Nemwel-Boniface commented on schema_based_on_diagram.sql
> +CREATE INDEX treatment_histories ON medical_histories(id);
- [ ] I have seen that you have one index created at line 21 as you @Farida-Hamid  have said. However, according to the project requirements, you are required to create indexes for all the foreign keys for all the tables in your project. What this means is that you need to have a total of six indexes, this includes the 5 primary tables plus one for the join table. I hope this is much clearer now for your team.

![image](https://user-images.githubusercontent.com/86318284/200777773-fb0d09d5-7401-4eab-a4b8-4d221aa3a668.png)

2022-11-09 09:02 UTC, gemmen29 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯  
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-09 09:02 UTC, gemmen29 commented on schema_based_on_diagram.sql
> +    );
- [ ] Kindly add indexes for those two foreign keys(`medical_history_id`, `treatment_id`) for the table `medical_histories_has_treatments` as requested by the previous reviewers.

2022-11-09 09:33 UTC, codecaiine approved these changes
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Goo database setup :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-12 10:16 UTC, merged